version: "3"
services:
       node-apis:
           container_name: node-apis
           image: latest123/node-apis
           restart: unless-stopped
           build: .
           ports:
             - "8080:8080"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'